---

h1:
  font-family: Karla
  font-weight: '700'
  font-size: 60px
  line-height: 70px

h2-light:
  font-family: Karla
  font-size: 32px
  line-height: 38px
h2:
  font-family: Karla
  font-weight: '700'
  font-size: 32px
  line-height: 38px

h3-light:
  font-family: Karla
  font-size: 24px
  line-height: 30px
h3:
  font-family: Karla
  font-weight: '700'
  font-size: 24px
  line-height: 30px

body:
  font-family: Karla
  font-size: 18px
  line-height: 24px

small: 
  font-family: Karla
  font-size: 14px
  line-height: 20px

