---
url: http://gilmanbrewing.com/
title: title placeholder
description: description placeholder
keywords: keywords
trackingID: UA-77714389-1
share: img/share.jpg
repo: http://www.github.com/acidjazz/gilman
address:
  map: https://goo.gl/maps/E358TP48W4G2
  street: 912 Gilman St
  city: Berkeley
  state: CA
  zip: 93710
  country: US
  phone: (510) 556-8701
email: info@gilmanbrewing.com
social:
  facebook: https://www.facebook.com/AnvilBrewingCompany/
  twitter: https://twitter.com/Gilman_Brewing
  instagram: https://www.instagram.com/gilmanbrewing/
