---
url: http://gilmanbrewing.com/
title: Gilman Brewing Company
description: Gilman Brewing Company and Taproom, born and brewed in Berkeley, California. Founded in 2016, we specialize in craft beers, ales, stouts and lagers. Drink responsibly.
keywords: beer, ale, craft brew, stouts, lagers, spirits, berkeley, california, gilman, brewery, pub, IBUs, taproom, bay area
trackingID: UA-77714389-2
share: images/share.jpg
repo: https://github.com/acidjazz/gilman
address:
  map: https://goo.gl/maps/E358TP48W4G2
  street: 912 Gilman St
  city: Berkeley
  state: CA
  zip: 93710
  country: US
  phone: (510) 556-8701
email: info@gilmanbrew.com
social:
  facebook: https://www.facebook.com/AnvilBrewingCompany/
  twitter: https://twitter.com/Gilman_Brewing
  instagram: https://www.instagram.com/gilmanbrewing/
